#!/usr/bin/env python3
"""Build SCOREBOARD.md from logs/trial-log.csv. Deterministic: same CSV, same file.

Usage:
  scripts/scoreboard.py            # writes jarvis/SCOREBOARD.md
  scripts/scoreboard.py --stdout   # print instead of writing
"""

from __future__ import annotations

import argparse
import csv
import sys
from collections import Counter, defaultdict
from pathlib import Path

JARVIS_DIR = Path(__file__).resolve().parent.parent
CSV_PATH = JARVIS_DIR / "logs" / "trial-log.csv"
OUT_PATH = JARVIS_DIR / "SCOREBOARD.md"
SHIP_BAR = 14
PROTOCOL_TRIALS = 20


def load_rows(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open(newline="") as f:
        return [r for r in csv.DictReader(f) if r.get("skill")]


def build(rows: list[dict]) -> str:
    # group by (skill, date, policy): one protocol session
    sessions: dict[tuple[str, str, str], list[dict]] = defaultdict(list)
    for r in rows:
        sessions[(r["skill"], r["date"], r.get("policy_id", ""))].append(r)

    shipped: list[tuple] = []
    in_progress: dict[str, tuple] = {}
    regression: list[tuple] = []
    for (skill, date, policy), trials in sorted(sessions.items()):
        wins = sum(1 for t in trials if t.get("result") == "success")
        n = len(trials)
        fails = Counter(t.get("fail_category") or "-" for t in trials if t.get("result") != "success")
        top_fail = fails.most_common(1)[0][0] if fails else "-"
        notes = " ".join(sorted({t.get("notes", "") for t in trials if "regression" in t.get("notes", "")}))
        if notes:
            regression.append((date, skill, f"{wins}/{n}", notes))
            continue
        video = next((t.get("video_ref", "") for t in trials if t.get("video_ref")), "")
        if n >= PROTOCOL_TRIALS and wins >= SHIP_BAR:
            shipped.append((skill, f"{wins}/{n}", date, policy, "pending", video))
        # latest session per skill for the in-progress table
        in_progress[skill] = (skill, f"{wins}/{n}", date, policy, str(n), top_fail)

    best_shipped: dict[str, tuple] = {}
    for row in shipped:
        cur = best_shipped.get(row[0])
        if cur is None or int(row[1].split("/")[0]) > int(cur[1].split("/")[0]):
            best_shipped[row[0]] = row

    def table(header: list[str], body: list[tuple]) -> str:
        lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
        if not body:
            lines.append("|" + " |" * len(header))
        for row in body:
            lines.append("| " + " | ".join(str(c) for c in row) + " |")
        return "\n".join(lines)

    parts = [
        "# Jarvis scoreboard",
        "",
        "Generated by `jarvis/scripts/scoreboard.py` from `jarvis/logs/trial-log.csv`. Do not edit by hand.",
        "",
        f"## Shipped skills (L2, {SHIP_BAR}/{PROTOCOL_TRIALS} or better)",
        "",
        table(
            ["Skill", "Best score", "Date", "Policy", "Cold test", "Video"],
            sorted(best_shipped.values()),
        ),
        "",
        "## In progress",
        "",
        table(
            ["Skill", "Latest score", "Date", "Policy", "Trials so far", "Top fail category"],
            sorted(in_progress.values()),
        ),
        "",
        "## Regression runs",
        "",
        table(["Date", "Skill", "Score", "Notes"], sorted(regression)),
        "",
        "## Safety gate latencies (last session)",
        "",
        table(
            ["Gate", "Result", "Latency"],
            [
                ("SG1 e-stop", "", ""),
                ("SG2 button", "", ""),
                ("SG3 stop word", "", ""),
                ("SG4 LLM stop", "", ""),
            ],
        ),
        "",
    ]
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--stdout", action="store_true")
    ap.add_argument("--csv", type=Path, default=CSV_PATH)
    args = ap.parse_args()
    text = build(load_rows(args.csv))
    if args.stdout:
        sys.stdout.write(text)
    else:
        OUT_PATH.write_text(text)
        print(f"wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
